name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/project/forum-app-backend
          git pull origin master
          /home/alfyandoo/.nvm/versions/node/v16.20.0/bin/npm install
          /home/alfyandoo/.nvm/versions/node/v16.20.0/bin/npm run migrate up
          /home/alfyandoo/.nvm/versions/node/v16.20.0/bin/pm2 restart forumapi:5000