name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_USER: rnwlbtarfufeoa
          POSTGRES_PASSWORD: f1e5c484719b2f0538e382fcf66d59d9f0a5dc5ad882680eb16559b1a7d3884d
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://rnwlbtarfufeoa:f1e5c484719b2f0538e382fcf66d59d9f0a5dc5ad882680eb16559b1a7d3884d@ec2-54-208-139-247.compute-1.amazonaws.com:5432/d78g9ursf7fn03
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run migrate:test up
      - run: npm run test